---
Name: silverstripe-search-service-elastic
Only:
  envvarset: 'ELASTICSEARCH_ENDPOINT'
After:
  - 'silverstripe-search-service-dataobject'
  - 'search-service-default'
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Service\IndexConfiguration:
    constructor:
      index_variant: '`ELASTICSEARCH_INDEX_PREFIX`'
  SilverStripe\SearchService\Interfaces\IndexingInterface:
    class: SilverStripe\SearchServiceElastic\Service\ElasticsearchService
    constructor:
      client: '%$Elastic\Elasticsearch\Client'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      builder: '%$SilverStripe\SearchService\Service\DocumentBuilder'
  Elastic\Elasticsearch\Client:
    factory: SilverStripe\SearchServiceElastic\Service\ClientFactory
    constructor:
      host: '`ELASTICSEARCH_ENDPOINT`'
      username: '`ELASTICSEARCH_USERNAME`'
      password: '`ELASTICSEARCH_PASSWORD`'
      http_client: '%$GuzzleHttp\Client'

## customise the dataobject fields for Elasticsearch compatibility
SilverStripe\SearchService\DataObject\DataObjectDocument:
  id_field: record_id
  base_class_field: record_base_class
  page_content_field: page_content
